### ISSUE TITLE
Fix README Link to Simon Willison's Blog

### ISSUE THREAD

**Issue by madEng84** [bfirsh/django-shorturls#27]
The link [http://blog.simonwillison.net/post/57956849396/revcanonical/](http://blog.simonwillison.net/post/57956849396/revcanonical/) does not work
You have to replace it with [http://blog.simonwillison.net/post/57956849396/revcanonical](http://blog.simonwillison.net/post/57956849396/revcanonical) or better with [https://simonwillison.net/2009/Apr/11/revcanonical/](https://simonwillison.net/2009/Apr/11/revcanonical/)

**Comment by bfirsh** [comment]
Nice, thank you!

@simonw Looks like your old redirects don't work if there is a trailing slash on them.
